salesforce.username=vianavitor232.1398081901cc@agentforce.com
salesforce.password=?=ZHke,:66FX7Hc
salesforce.securityToken=r5E1JMxVBfrRmKbR3O3UhAxhA
http.port=8081
#salesforce.versionUrl="https://login.salesforce.com/services/Soap/u/64.0"